### ISSUE TITLE
Do you plan to upload source for system?

### ISSUE THREAD

**Issue by markwjkelly** [sparkfun/SparkFun_DataLogger_IoT_9DoF#2]
We are exploring using the Datalogger_IoT_9DoF. We deploy our systems in secured locations and need to be able to present our source code as part of the project to get clearance.  Do you plan to release the code for this system, or do we need to create our software solution?

**Comment by PaulZC** [comment]
Hello @markwjkelly ,

Thank you for your interest in the DataLogger.

We are keeping the DataLogger firmware closed-source as it contains SparkFun Intellectual Property and is the result of hundreds of hours of work. We may be able to release it to you, but it would be under a Non-Disclosure Agreement and only if the projected sales make it viable. Is this something you would be interested in pursuing? If so, please send me your full contact details - you will find my address on my profile page.

Best wishes,
Paul

**Comment by gigapod** [comment]
@markwjkelly  - I want to follow-up on Paul's message. We're happy to support your  effort to have the firmware reviewed for product use in a classified environment.  If interested, reply here and we can connect to discuss further. 

Regards,
-Kirk

**Comment by tedivm** [comment]
So Sparkfun is no longer open source? Why are you still advertising it as open source?

<img width="570" alt="Screenshot 2023-07-19 at 1 10 38 PM" src="https://github.com/sparkfun/SparkFun_DataLogger_IoT_9DoF/assets/121709/6c54e38d-ffec-4c28-9ed8-8ca1045377b7">

<img width="428" alt="Screenshot 2023-07-19 at 1 11 06 PM" src="https://github.com/sparkfun/SparkFun_DataLogger_IoT_9DoF/assets/121709/f21c49a2-82e8-4270-bea2-0c3880982c7e">


If you made the decision to keep this "closed source" but are advertising it as "open hardware" then you're lying to the community. This is the literal definition of false advertising. Either do the right thing and open up the software, or please consider being honest on your website.
